### ISSUE TITLE
Change/edit wallpaper bug

### ISSUE THREAD

**Issue by qnblackcat** [Nosskirneh/SpringArtwork-Public#2]
- If i change/edit wallpaper during music are playing, it will mess up SpringArtwork
https://imgur.com/qe9pqpK
=> artwork no more auto change, kill Music app doenst bring back stock wallpaper 
=> everything will be back to normal after Respring (or change/edit wallpaper again)

Music App, iPhone 6s-12.2-unc0ver

**Comment by Nosskirneh** [comment]
Hi again!

Sorry for the late reply; I've been busy with exams. This bug has been fixed and the fix will be available in the next update. Thanks for reporting!
