### ISSUE TITLE
Canvas video not playing

### ISSUE THREAD

**Issue by iCrackYourDevice** [Nosskirneh/SpringArtwork-Public#3]
I have the video option enabled on Spring artwork, but the tweak doesn't play the Spotify canvas artwork video. Spring artwork only displays the album wallpaper. I’m on my ios 13.3 iPhone XS Max, I’m using the free trial of the latest version of Spring artwork.

**Comment by Nosskirneh** [comment]
Hmm. Does Spotify show the canvas?
It might be the communication between Spotify and SpringBoard not working as it should. If you install NextUp, does it work? I’m asking because it uses the same communication mechanism.

**Comment by iCrackYourDevice** [comment]
Spotify does show the canvas and with NextUp does not work with my Spotify.

**Comment by Nosskirneh** [comment]
Are you using the default Spotify app? Unofficial copies of Spotify use completely different bundle IDs.

**Comment by iCrackYourDevice** [comment]
I didn’t realize I was not using the default app. It’s working now. Thank you!
