### ISSUE TITLE
“Disabled apps” doesn’t really work

### ISSUE THREAD

**Issue by bushysowavvey** [Nosskirneh/SpringArtwork-Public#4]
I’ve disabled YouTube because I don’t like seeing YouTube thumbnails on my springboard along with some podcast apps, and they just seem to stay there no matter what I disable and respring. 

Also, I tried to disable the spring artwork completely and it still came back.

**Comment by Nosskirneh** [comment]
Yes, I should push a new version with a fix. Other things got in the way :/

**Comment by bushysowavvey** [comment]
Please that’d be very much appreciated 🙏🏾

**Comment by Nosskirneh** [comment]
beta13 should fix this. Feel free to reopen this issue if you’re still facing the issue.
